import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from utils import apply_page_style, get_monthly_series, kpi_card, load_data, sidebar_branding, train_and_forecast

st.set_page_config(page_title="Forecast Explorer", page_icon="📈", layout="wide")
apply_page_style()
sidebar_branding("Forecast Explorer")

df = load_data()

# --------------------------------------------------------------------------
# SIDEBAR CONTROLS
# --------------------------------------------------------------------------
st.sidebar.subheader("🔎 Forecast Controls")

dimension = st.sidebar.radio("Forecast by", ["Category", "Region"], key="fx_dim")

if dimension == "Category":
    options = ["All"] + sorted(df["Category"].unique().tolist())
    selection = st.sidebar.selectbox("Select Category", options, key="fx_cat")
    category, region = selection, "All"
else:
    options = ["All"] + sorted(df["Region"].unique().tolist())
    selection = st.sidebar.selectbox("Select Region", options, key="fx_reg")
    category, region = "All", selection

horizon = st.sidebar.slider("Forecast Horizon (months ahead)", min_value=1, max_value=3, value=3, key="fx_horizon")

st.sidebar.info("Forecasting model: **XGBoost** — selected as the best-performing "
                 "model in Task 3 model comparison (lowest MAE/RMSE/MAPE).")

# --------------------------------------------------------------------------
# HEADER
# --------------------------------------------------------------------------
st.markdown('<p class="page-title">📈 Forecast Explorer</p>', unsafe_allow_html=True)
st.markdown(
    f'<p class="page-subtitle">Forecasting <b>{selection}</b> sales for the next '
    f'<b>{horizon} month(s)</b> using the XGBoost model</p>',
    unsafe_allow_html=True,
)

monthly = get_monthly_series(df, category=category, region=region)

if monthly.sum() == 0 or len(monthly.dropna()) < 15:
    st.warning("Not enough historical data for this selection to train a reliable forecast.")
    st.stop()

with st.spinner("Training model and generating forecast..."):
    result = train_and_forecast(monthly, horizon=horizon, test_size=6)

forecast = result["forecast"]
mae, rmse, mape = result["mae"], result["rmse"], result["mape"]

# --------------------------------------------------------------------------
# KPI ROW — MODEL PERFORMANCE
# --------------------------------------------------------------------------
c1, c2, c3, c4 = st.columns(4)
with c1:
    kpi_card("MAE", f"${mae:,.0f}")
with c2:
    kpi_card("RMSE", f"${rmse:,.0f}")
with c3:
    kpi_card("MAPE", f"{mape:,.1f}%")
with c4:
    kpi_card("Next Month Forecast", f"${forecast.iloc[0]:,.0f}")

st.write("")

# --------------------------------------------------------------------------
# ACTUAL vs FORECAST CHART
# --------------------------------------------------------------------------
st.markdown('<div class="section-card">', unsafe_allow_html=True)
st.subheader("📊 Actual Sales vs Forecast")

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=monthly.index, y=monthly.values, mode="lines+markers",
    name="Actual Sales", line=dict(color="#0E4C92", width=2),
))
fig.add_trace(go.Scatter(
    x=forecast.index, y=forecast.values, mode="lines+markers",
    name="Forecast", line=dict(color="#E67E22", width=2, dash="dash"),
))
fig.add_vline(x=monthly.index[-1], line_dash="dot", line_color="gray")
fig.update_layout(
    xaxis_title="Month", yaxis_title="Sales ($)",
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    hovermode="x unified",
)
st.plotly_chart(fig, width="stretch")
st.markdown("</div>", unsafe_allow_html=True)

# --------------------------------------------------------------------------
# FORECAST TABLE
# --------------------------------------------------------------------------
col_left, col_right = st.columns([1, 1])

with col_left:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader("🗓️ Forecast Values")
    forecast_table = pd.DataFrame({
        "Month": forecast.index.strftime("%B %Y"),
        "Forecasted Sales": forecast.values.round(2),
    })
    st.dataframe(forecast_table, width="stretch", hide_index=True)
    st.markdown("</div>", unsafe_allow_html=True)

with col_right:
    st.markdown('<div class="section-card">', unsafe_allow_html=True)
    st.subheader("🎯 Hold-out Test: Actual vs Predicted")
    test_actual = result["test_actual"]
    test_pred = result["test_pred"]
    test_table = pd.DataFrame({
        "Month": test_actual.index.strftime("%b %Y"),
        "Actual": test_actual.values.round(2),
        "Predicted": test_pred.values.round(2),
    })
    st.dataframe(test_table, width="stretch", hide_index=True)
    st.markdown("</div>", unsafe_allow_html=True)

with st.expander("ℹ️ About this model"):
    st.write(
        """
        The forecast is generated by an **XGBoost Regressor** trained on lag features
        (1, 2, and 3 months back), a 3-month rolling mean, and calendar features
        (Month, Quarter, Season). Metrics above (MAE, RMSE, MAPE) are computed on a
        held-out tail of the historical series and reflect how the model performed on
        unseen data before being refit on the full series to produce the forecast shown.
        """
    )

st.markdown(
    '<div class="footer">Page 2 of 4 — Forecast Explorer</div>', unsafe_allow_html=True
)